name: 🐞 Bug Report
description: Create a new bug report.
title: '🐞 bug: <title>'
labels: [Bug, Needs Triage]
body:

  - type: markdown
    attributes:
      value: ':stop_sign: _Make sure you are reporting an issue. For general questions, please refer to our documentation or discussion forums._'

  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: 'Please [search :mag: the issues](/issues) to check if this bug has already been reported.'
      options:
      - label: I have searched the existing issues
        required: true

  - type: checkboxes
    attributes:
      label: Is this issue reproducible using the latest version?
      description: |
        Please ensure you are using the latest version before reporting bugs.
      options:
      - label: I confirm the issue is reproducible with the latest version

  - type: textarea
    attributes:
      label: Current Behavior
      description: Describe the problem you are experiencing. **Please do not paste your logs here.** Screenshots are welcome.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behavior
      description: Describe what you expect to happen instead.
    validations:
      required: true

  - type: input
    attributes:
      label: Logs
      description: |
        Please create a [Gist](https://gist.github.com) with your logs and link it here. Alternatively, you can directly attach your logfile in the "Further Information" field below.

        :warning: _Remember to redact or remove any sensitive information!_
      placeholder: 'https://gist.github.com/...'

  - type: textarea
    attributes:
      label: Environment Details
      description: |
        Please provide information about your environment; feel free to remove any items which are not relevant.

        :warning: _Remember to redact or remove any sensitive information!_
      value: |
          - Operating System and version:
          - Project version:
          - Browser/client (if applicable):
          - Last version which did _not_ exhibit the problem (if known):

  - type: textarea
    attributes:
      label: Minimal Reproducible Example
      description: |
        Please provide [the smallest, complete code snippet](https://stackoverflow.com/help/minimal-reproducible-example) that can reproduce the issue. Failing this, any sort of reproduction steps are better than nothing!

        If the result is more than a screenful of text _or_ requires multiple files, please:

        - _Attach_ (do not paste) it to this textarea, _or_
        - Put it in a [Gist](https://gist.github.com) and paste the link, _or_
        - Provide a link to a new or existing public repository exhibiting the issue
    validations:
      required: true

  - type: textarea
    attributes:
      label: Further Information
      description: If needed, please provide additional information about your issue (attachments, links, references, etc.).

  - type: markdown
    attributes:
      value: ':stop_sign: _Thank you for taking the time to fill out this bug report._'